### ISSUE TITLE
panics when trying to run

### ISSUE THREAD

**Issue by matthiaskrgr** [kennytm/rustup-toolchain-install-master#8]
v `v1.2.0`

````
 RUST_BACKTRACE=full rustup-toolchain-install-master -n master  -f
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
stack backtrace:
   0:     0x560a2cfb0a0e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hf6a90546f230a7d0
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x560a2cfa19e6 - std::sys_common::backtrace::print::hb75e59ddca9a1b7a
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x560a2cf9fcbd - std::panicking::default_hook::{{closure}}::h35bf369726f7ef7f
                               at libstd/panicking.rs:211
   3:     0x560a2cf9fa30 - std::panicking::default_hook::ha71a2a7fa5235450
                               at libstd/panicking.rs:227
   4:     0x560a2cfa032c - std::panicking::rust_panic_with_hook::h7d7e0e1ff988fee8
                               at libstd/panicking.rs:477
   5:     0x560a2cf9ff29 - std::panicking::continue_panic_fmt::he8d778b183a54215
                               at libstd/panicking.rs:391
   6:     0x560a2cf9fe25 - rust_begin_unwind
                               at libstd/panicking.rs:326
   7:     0x560a2cff8f1b - core::panicking::panic_fmt::h1c54d6121d2e9db5
                               at libcore/panicking.rs:77
   8:     0x560a2cff8e4a - core::panicking::panic::he4a84d173432c46d
                               at libcore/panicking.rs:52
   9:     0x560a2cf1ac34 - openssl::ssl::connector::ctx::h3b1144d6095d7f49
  10:     0x560a2cf1ac73 - openssl::ssl::connector::SslConnectorBuilder::new::h988528bab3697168
  11:     0x560a2cf19227 - native_tls::TlsConnector::builder::h7472044297d7c860
  12:     0x560a2cec611a - reqwest::async_impl::client::ClientBuilder::new::heee6c4a5a398a3d0
  13:     0x560a2ce79732 - reqwest::client::ClientBuilder::new::h580aea3999060b52
  14:     0x560a2cdf153f - rustup_toolchain_install_master::run::ha58f29e5809cc628
  15:     0x560a2cdf5f85 - rustup_toolchain_install_master::main::h366deb6f9b21c6d1
  16:     0x560a2cde4fd2 - std::rt::lang_start::{{closure}}::h977401b7b9fc0d1a
  17:     0x560a2cf9fdc2 - std::panicking::try::do_call::h7120cc99658f0544
                               at libstd/rt.rs:59
                               at libstd/panicking.rs:310
  18:     0x560a2cfc1879 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  19:     0x560a2cfac645 - std::rt::lang_start_internal::he861fec101d426ef
                               at libstd/panicking.rs:289
                               at libstd/panic.rs:392
                               at libstd/rt.rs:58
  20:     0x560a2cdf5fd3 - main
  21:     0x7fd5f68e2222 - __libc_start_main
  22:     0x560a2cde202d - _start
  23:                0x0 - <unknown>
````

**Comment by kennytm** [comment]
I suspect your OpenSSL isn't properly configured.

Anyway I've updated `reqwest` in 1.3.0, could you retry with the latest version?

**Comment by matthiaskrgr** [comment]
My distro has 2 openssl versions coninstalled at the same time (1.1.1 and 1.0.2) which probably confused something in the code.
Anyway, I can confirm that the update fixed the build as well as the runtime panic, thanks!
